drummersoul/Cryptocurrency-Price-Prediction

Python files/Data_understanding.py

Imported Pandas and wrote lines to find the rows and shape of the dataset.

imported pandas and statements to structure the data

---

Python files/Data_understanding.py

Added Matplotlib for plotting the data

Added Matplotlib for plotting the data

---

Python files/Data_understanding.py

visualize data distribution to see patterns in open, close prices

pull request from janani_week_five

---

Python files/Data_understanding.py
Python files/basic_plot.py

1. date_format issue fix
2. getting mean issue fix
3. Added practice code

Venkat week five

---

Python files/.idea/.gitignore
Python files/.idea/Python files.iml
Python files/.idea/inspectionProfiles/profiles_settings.xml
Python files/.idea/misc.xml
Python files/.idea/modules.xml
Python files/.idea/vcs.xml
Python files/.idea/workspace.xml
Python files/Data_understanding.py

Added a Boxplot to show open price with outliers horizontally with title and label.

Urjeet week five

---

.idea/Cryptocurrency-Price-Prediction.iml
.idea/misc.xml
Python files/Data_understanding.py

Cleaned the code using a pep-8 styling formatter.

Code Cleaning

---

Python files/Data_understanding.py

1. Removed Duplicate code
2. Resolved issue fix 
3. Added Correlation HeatMap of LiteCoin

Venkat week six

---

Python files/Data_understanding.py

created new features 7-day moving average, 30-day moving average, difference from previous day using close price

PR from branch janani_week_six

---

Python files/Data_understanding.py
Python files/graphs.py
Python files/utils/utils.py

Instantiating Graph Class into our Data Understanding Script

Bibek week seven

---

Python files/Data_understanding.py

Spliitted data and added Logistic Regression

Spliitted data and added Logistic Regression

---

Python files/Data_understanding.py

added code to train a XGBClassifier to predict target variable

pr janani_week_seven

---

.idea/Cryptocurrency-Price-Prediction.iml
.idea/misc.xml
Python files/utils/utils.py

fixing error when locating the excel file as it was searich for it inside the python folder, so fixed the code to first return one folder.

Get Data function error fix

---

Python files/Data_understanding.py
Python files/Ml_Models.py
Python files/main.py
Python files/utils/utils.py

1. Created New Class for Models in the code
2. added Main file for data cleaning

DataCleaning for Ml models

---

.idea/Cryptocurrency-Price-Prediction.iml
.idea/misc.xml
Python files/Data_understanding.py
Python files/Untitled.ipynb

xgb_code_fix for printing the test and train results

xgb_code_fix

---

Python files/.idea/workspace.xml
Python files/Data_understanding.py
Python files/utils/utils.py

Applying L1 and L2 regularization for XGB

Applying L1 and L2 regularization for XGB

---

Python files/Data_understanding.py

modifying the learning rate from default to 0.01

modifying the learning rate

---

Python files/Data_understanding.py

Add max_depth param to xgb

---

.idea/Cryptocurrency-Price-Prediction.iml
.idea/misc.xml
Python files/Data_understanding.py

Incorrect order of variable assign when doing data splitting

fixed data splitting varaible assign

---

Python files/Data_understanding.py

grouped code for new features together

pr_janani week nine

---

Python files/Data_understanding.py

implement meta prophet for time series

implement meta prophet for time series

---

Python files/Data_understanding.py

Added Plot to show forecasting

Added Plot to show forecasting

---

Python files/Data_understanding.py

Implented Time series  on splitted data to forecast after splitter date and fixed bugs regarding Meta Prophet library.

Implented Time series  on splitted data to forecast after splitter date

---

Python files/Data_understanding.py
Python files/Ml_Models.py

basic code for classification metrics

pr janani_week_ten

---

Python files/.idea/workspace.xml
Python files/Data_understanding.py
Python files/Ml_Models.py

Plotting ROC curve for logistic and XGBoost.

Plotting ROC curve

---

Python files/Data_understanding.py
Python files/graphs.py

1. Added **show_figure** argument in all Functions in Graph Class
2. **show_figure** will check weather to display graph or not when particular function in called
3. Added logic to check the argument

added new feature to show figure or not

---

Python files/Data_understanding.py

Just Added Holiday Effect to time series model ,which shows how much the price or market was affected on the day of holiday in a particular selected country.

Added Holiday Effect on Prophet Model

---

Python files/Data_understanding.py
Python files/Ml_Models.py
Python files/graphs.py

Random Forest model added with confusion matrix and roc curve

Random Forest model added with confusion matrix and roc curve

---

Python files/Data_understanding.py
Python files/Ml_Models.py

Perform Grid Search for XGBoost

Perform Grid Search for XGBoost

---

Python files/Data_understanding.py

Looked for missing dates  according to group leaders observation. And made a observation that many dates are missing which is breaking the time period

Looked for missing dates.

---

Python files/Data_understanding.py
Python files/Ml_Models.py

Added Grid Search For Logistic Regression

Added Grid Search For Logistic Regression

---

Python files/Data_understanding.py

A type of Cross-Validation used for Time-Dependent Data.

Added Time-Seriessplit CV

---

Python files/Data_understanding.py

linear interpolation of missing dates.

linear interpolation of missing dates.

---

src/data_understanding.py

Create dashboard instance and add the correct Title

Create dashboard instance and add the correct Title

---

src/data_understanding.py
src/utils/utils.py

added streamlit container to dataframe  and heatmap historical data graph

added streamlit container

---

src/data_understanding.py

created two new features and shifting target before split

created two new features and shifting target after split

---

src/dashboard.py
src/data_understanding.py
src/graphs.py
src/lime.py
src/main.py
src/models/ml_models.py
src/utils/utils.py

Formated code according to PEP8 recomendations which included making some of the functions static as they do not use the instance self, removed lime

PEP8 format, static functions

---

src/data_understanding.py
src/main.py
src/models/ml_models.py
src/utils/utils.py

added pathlib for dashboard deploy, changed features for model training

added pathlib for dashboard deploy, changed features for model training

---

src/dashboard.py
src/utils/utils.py

Made font Resonsive with theme added dynamic date option to dashboard

Made font Resonsive with theme added dynamic date option
